name: VIRAJ TESTING

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'
          cache: maven

      - name: Run Cucumber tests
        run: mvn test -s maven-settings-central.xml

      - name: Publish test summary
        if: always()
        run: |
          echo "## Cucumber Results" >> $GITHUB_STEP_SUMMARY
          echo "See full HTML report in Artifacts below." >> $GITHUB_STEP_SUMMARY

      - name: Upload Cucumber HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-report
          path: target/cucumber-reports.html
